# Generated by Django 5.1 on 2024-09-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_remove_cardset_description_alter_cardset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
