# Generated by Django 5.1 on 2024-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_cardset_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='last_review',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
