# Generated by Django 5.1 on 2024-09-04 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_review', models.DateField(auto_now=True)),
                ('language', models.CharField(blank=True, choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_set',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_review', models.DateField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('cardset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.cardset')),
            ],
        ),
    ]
