# Generated by Django 5.0.6 on 2024-08-18 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('type', models.CharField(choices=[('order-sentence', 'Order sentence'), ('listen-term', 'Listen term'), ('listen-term-mchoice', 'Listen term mulitple choice'), ('listen-sentence', 'Listen sentence'), ('speak-term', 'Speak term'), ('speak-sentence', 'Speak sentence'), ('mchoice-term', 'Mulitple choice term'), ('mchoice-term-definition', 'Multiple choice term definition'), ('random', 'Random')], max_length=50)),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition')),
                ('term_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
                ('term_lexical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
                ('term_pronunciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termpronunciation')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'order-sentence')), fields=('type', 'language', 'term_example'), name='unique_order_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'listen-term')), fields=('type', 'language', 'term', 'term_pronunciation'), name='unique_listen_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'listen-term')), fields=('type', 'language', 'term', 'term_lexical', 'term_pronunciation'), name='unique_listen_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'listen-term-mchoice')), fields=('type', 'language', 'term', 'term_pronunciation'), name='unique_listen_term_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'listen-sentence')), fields=('type', 'language', 'term_example', 'term_pronunciation'), name='unique_listen_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'speak-term')), fields=('type', 'language', 'term'), name='unique_speak_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'speak-term')), fields=('type', 'language', 'term', 'term_lexical'), name='unique_speak_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'speak-sentence')), fields=('type', 'language', 'term_example'), name='unique_speak_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'mchoice-term')), fields=('type', 'language', 'term'), name='unique_mchoice_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'mchoice-term')), fields=('type', 'language', 'term', 'term_lexical'), name='unique_mchoice_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'mchoice-term-definition')), fields=('type', 'language', 'term_definition', 'term'), name='unique_mchoice_term_definition'),
        ),
        migrations.AddConstraint(
            model_name='exerciselevel',
            constraint=models.UniqueConstraint(models.F('exercise'), models.F('level'), name='unique_exercise_level'),
        ),
    ]
