# Generated by Django 5.1 on 2024-09-04 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('type', models.CharField(choices=[(0, 'Order sentence'), (1, 'Listen term'), (2, 'Listen term mulitple choice'), (3, 'Listen sentence'), (4, 'Speak term'), (5, 'Speak sentence'), (6, 'Mulitple choice term'), (7, 'Multiple choice term definition'), (8, 'Term image multiple choice'), (9, 'Term text image multiple choice'), (10, 'Term connection'), (12, 'Random')], max_length=50)),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition')),
                ('term_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
                ('term_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termimage')),
                ('term_lexical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
                ('term_pronunciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termpronunciation')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 0)), fields=('type', 'language', 'term_example'), name='unique_order_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 1)), fields=('type', 'language', 'term', 'term_pronunciation'), name='unique_listen_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 1)), fields=('type', 'language', 'term', 'term_lexical', 'term_pronunciation'), name='unique_listen_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 2)), fields=('type', 'language', 'term', 'term_pronunciation'), name='unique_listen_term_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 3)), fields=('type', 'language', 'term_example', 'term_pronunciation'), name='unique_listen_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 4)), fields=('type', 'language', 'term'), name='unique_speak_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 4)), fields=('type', 'language', 'term', 'term_lexical'), name='unique_speak_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 5)), fields=('type', 'language', 'term_example'), name='unique_speak_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 6)), fields=('type', 'language', 'term', 'term_example'), name='unique_term_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 6)), fields=('type', 'language', 'term', 'term_example', 'term_lexical'), name='unique_term_lexical_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 7)), fields=('type', 'language', 'term_definition', 'term'), name='unique_term_definition_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 8)), fields=('type', 'language', 'term', 'term_image', 'term_pronunciation'), name='unique_term_image_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 9)), fields=('type', 'language', 'term', 'term_image'), name='unique_term_image_text_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 10)), fields=('type', 'language', 'term'), name='unique_term_conection'),
        ),
        migrations.AddConstraint(
            model_name='exerciselevel',
            constraint=models.UniqueConstraint(models.F('exercise'), models.F('level'), name='unique_exercise_level'),
        ),
    ]
