# Generated by Django 5.0.6 on 2024-08-18 20:18

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('part_of_speech', models.CharField(choices=[('adjective', 'Adjective'), ('noun', 'Noun'), ('verb', 'Verb'), ('adverb', 'Adverb'), ('conjunction', 'Conjunction'), ('preposition', 'Preposition'), ('pronoun', 'Pronoun'), ('determiner', 'Determiner'), ('number', 'Number'), ('predeterminer', 'Predeterminer'), ('prefix', 'Prefix'), ('suffix', 'Suffix'), ('slang', 'Slang'), ('lexical', 'Lexical')], max_length=50)),
                ('definition', models.TextField()),
                ('level', models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermDefinitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('translation', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('example', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermExampleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('highlight', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TermExampleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('translation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermExampleTranslationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('translation_language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('highlight', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='TermLexical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('synonym', 'Synonym'), ('antonym', 'Antonym'), ('form', 'Form'), ('idiom', 'Idiom'), ('rhyme', 'Rhyme')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermPronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('phonetic', models.CharField(max_length=255)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('expression', models.CharField(max_length=256)),
                ('origin_language', models.CharField(choices=[('pt', 'Português'), ('en', 'Inglês'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('expression'), django.db.models.functions.text.Lower('origin_language'), name='term_inex_db')],
            },
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('expression'), django.db.models.functions.text.Lower('origin_language'), name='unique_term_expression'),
        ),
        migrations.AddField(
            model_name='termdefinition',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='termdefinitiontranslation',
            name='term_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition'),
        ),
        migrations.AddField(
            model_name='termexamplelink',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='termexamplelink',
            name='term_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition'),
        ),
        migrations.AddField(
            model_name='termexamplelink',
            name='term_example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termexample'),
        ),
        migrations.AddField(
            model_name='termexampletranslation',
            name='term_example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termexample'),
        ),
        migrations.AddField(
            model_name='termexampletranslationlink',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='termexampletranslationlink',
            name='term_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition'),
        ),
        migrations.AddField(
            model_name='termexampletranslationlink',
            name='term_example',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termexample'),
        ),
        migrations.AddField(
            model_name='termlexical',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='termlexical',
            name='term_value_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_ref', to='term.term'),
        ),
        migrations.AddField(
            model_name='termexampletranslationlink',
            name='term_lexical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical'),
        ),
        migrations.AddField(
            model_name='termexamplelink',
            name='term_lexical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical'),
        ),
        migrations.AddField(
            model_name='termdefinition',
            name='term_lexical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical'),
        ),
        migrations.AddField(
            model_name='termpronunciation',
            name='term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='termpronunciation',
            name='term_example',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termexample'),
        ),
        migrations.AddField(
            model_name='termpronunciation',
            name='term_lexical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical'),
        ),
        migrations.AddConstraint(
            model_name='termdefinitiontranslation',
            constraint=models.UniqueConstraint(models.F('language'), models.F('term_definition'), name='term_definition_translation_unique_translation'),
        ),
        migrations.AddConstraint(
            model_name='termexampletranslation',
            constraint=models.UniqueConstraint(models.F('language'), models.F('term_example'), name='term_example_translation_unique'),
        ),
        migrations.AddConstraint(
            model_name='termexampletranslationlink',
            constraint=models.UniqueConstraint(models.F('term'), models.F('term_example'), models.F('translation_language'), name='unique_term_example_translation_link'),
        ),
        migrations.AddConstraint(
            model_name='termexampletranslationlink',
            constraint=models.UniqueConstraint(models.F('term_definition'), models.F('term_example'), models.F('translation_language'), name='unique_term_definition_translation_link'),
        ),
        migrations.AddConstraint(
            model_name='termexampletranslationlink',
            constraint=models.UniqueConstraint(models.F('term_lexical'), models.F('term_example'), models.F('translation_language'), name='unique_term_lexical_translation_link'),
        ),
        migrations.AddConstraint(
            model_name='termexamplelink',
            constraint=models.UniqueConstraint(models.F('term'), models.F('term_example'), name='unique_term_example_link'),
        ),
        migrations.AddConstraint(
            model_name='termexamplelink',
            constraint=models.UniqueConstraint(models.F('term_definition'), models.F('term_example'), name='unique_term_definition_link'),
        ),
        migrations.AddConstraint(
            model_name='termexamplelink',
            constraint=models.UniqueConstraint(models.F('term_lexical'), models.F('term_example'), name='unique_term_lexical_link'),
        ),
    ]
