# Generated by Django 5.1 on 2024-09-22 18:12

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt-BR', 'Portuguese Brazil'), ('en-US', 'English USA'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('example', models.CharField(max_length=255)),
                ('level', models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('expression', models.CharField(max_length=256)),
                ('language', models.CharField(choices=[('pt-BR', 'Portuguese Brazil'), ('en-US', 'English USA'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('expression'), django.db.models.functions.text.Lower('language'), name='term_inex_db')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('expression'), django.db.models.functions.text.Lower('language'), name='unique_term_expression')],
            },
        ),
        migrations.CreateModel(
            name='TermImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='term')),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermLexical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[(0, 'Synonym'), (1, 'Antonym'), (2, 'Inflection'), (3, 'Idiom'), (4, 'Rhyme')], max_length=50)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_value_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_ref', to='term.term')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('part_of_speech', models.CharField(choices=[(0, 'Adjective'), (1, 'Noun'), (2, 'Verb'), (3, 'Adverb'), (4, 'Conjunction'), (5, 'Preposition'), (6, 'Pronoun'), (7, 'Determiner'), (8, 'Number'), (9, 'Predeterminer'), (10, 'Prefix'), (11, 'Suffix'), (12, 'Slang'), (13, 'Phrasal verb'), (14, 'Lexical')], max_length=50)),
                ('definition', models.TextField()),
                ('level', models.CharField(blank=True, choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50, null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_lexical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermPronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('phonetic', models.CharField(max_length=255)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.URLField(blank=True, null=True)),
                ('term', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_example', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
                ('term_lexical', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermDefinitionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt-BR', 'Portuguese Brazil'), ('en-US', 'English USA'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('translation', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('term_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('language'), models.F('term_definition'), name='term_definition_translation_unique_translation')],
            },
        ),
        migrations.CreateModel(
            name='TermExampleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt-BR', 'Portuguese Brazil'), ('en-US', 'English USA'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('translation', models.CharField(max_length=255)),
                ('term_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('language'), models.F('term_example'), name='term_example_translation_unique')],
            },
        ),
        migrations.CreateModel(
            name='TermExampleTranslationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(choices=[('pt-BR', 'Portuguese Brazil'), ('en-US', 'English USA'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('highlight', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition')),
                ('term_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
                ('term_lexical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('term'), models.F('term_example'), models.F('language'), name='unique_term_example_translation_link'), models.UniqueConstraint(models.F('term_definition'), models.F('term_example'), models.F('language'), name='unique_term_definition_translation_link'), models.UniqueConstraint(models.F('term_lexical'), models.F('term_example'), models.F('language'), name='unique_term_lexical_translation_link')],
            },
        ),
        migrations.CreateModel(
            name='TermExampleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('highlight', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition')),
                ('term_example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
                ('term_lexical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('term'), models.F('term_example'), name='unique_term_example_link'), models.UniqueConstraint(models.F('term_definition'), models.F('term_example'), name='unique_term_definition_link'), models.UniqueConstraint(models.F('term_lexical'), models.F('term_example'), name='unique_term_lexical_link')],
            },
        ),
    ]
