# Generated by Django 5.0.6 on 2024-08-17 00:25

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        # Adicione as dependências da sua migração aqui
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE EXTENSION IF NOT EXISTS unaccent;
            CREATE OR REPLACE FUNCTION clean_text(text_value TEXT)
            RETURNS TEXT AS
            $$
            BEGIN
                RETURN lower(unaccent(text_value));
            END;
            $$
            LANGUAGE plpgsql
            IMMUTABLE;
            """,
            reverse_sql="""
            DROP FUNCTION IF EXISTS clean_text(text_value TEXT);
            DROP EXTENSION IF EXISTS unaccent;
            """
        ),
    ]
