# Generated by Django 5.1 on 2024-09-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper Intermediate'), ('C1', 'Advanced'), ('C2', 'Master')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('pt-BR', 'Portuguese Brazil'), ('en-US', 'English USA'), ('de', 'Deutsch'), ('fr', 'Francês'), ('es', 'Espanhol'), ('it', 'Italiano'), ('zh', 'Chinese'), ('ja', 'Japonês'), ('ru', 'Russo')], max_length=50)),
                ('type', models.CharField(choices=[(0, 'Order sentence'), (1, 'Listen term'), (2, 'Listen term mulitple choice'), (3, 'Listen sentence'), (4, 'Speak term'), (5, 'Speak sentence'), (6, 'Mulitple choice term'), (7, 'Multiple choice term definition'), (8, 'Term image multiple choice'), (9, 'Term text image multiple choice'), (10, 'Term connection'), (12, 'Random')], max_length=50)),
                ('additional_content', models.JSONField(blank=True, null=True)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.term')),
                ('term_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termdefinition')),
                ('term_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termexample')),
                ('term_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termimage')),
                ('term_lexical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termlexical')),
                ('term_pronunciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='term.termpronunciation')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correct', models.BooleanField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercise')),
            ],
        ),
    ]
