# Generated by Django 5.1 on 2024-09-22 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciselevel',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 0)), fields=('type', 'language', 'term_example'), name='unique_order_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 1)), fields=('type', 'language', 'term', 'term_pronunciation'), name='unique_listen_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 1)), fields=('type', 'language', 'term_lexical', 'term_pronunciation'), name='unique_listen_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 2)), fields=('type', 'language', 'term', 'term_pronunciation'), name='unique_listen_term_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 3)), fields=('type', 'language', 'term_example', 'term_pronunciation'), name='unique_listen_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 4)), fields=('type', 'language', 'term'), name='unique_speak_term'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 4)), fields=('type', 'language', 'term_lexical'), name='unique_speak_term_lexical'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 5)), fields=('type', 'language', 'term_example'), name='unique_speak_sentence'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 6)), fields=('type', 'language', 'term', 'term_example'), name='unique_term_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 6)), fields=('type', 'language', 'term_example', 'term_lexical'), name='unique_term_lexical_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 7)), fields=('type', 'language', 'term_definition', 'term'), name='unique_term_definition_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 8)), fields=('type', 'language', 'term', 'term_image', 'term_pronunciation'), name='unique_term_image_mchoice'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 9)), fields=('type', 'language', 'term', 'term_image'), name='unique_term_image_mchoice_text'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 10)), fields=('type', 'language', 'term'), name='unique_term_conection'),
        ),
        migrations.AddConstraint(
            model_name='exerciselevel',
            constraint=models.UniqueConstraint(models.F('exercise'), models.F('level'), name='unique_exercise_level'),
        ),
    ]
